# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: syft

on:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: axios/axios 
        persist-credentials: false

    - uses: anchore/sbom-action@9246b90769f852b3a8921f330c59e0b3f439d6e9 # v0.20.1
      with:
        path: .
        output-file: syft-sbom.spdx.json
        upload-artifact: true

    - run: |
        cat syft-sbom.spdx.json
